# FROM ghcr.io/puppeteer/puppeteer:23.3.1


# ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
#     PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable
# WORKDIR /usr/src/app
# COPY package*.json ./
# COPY . .
# CMD ["node","telegramBot.js"]

FROM ghcr.io/puppeteer/puppeteer:23.3.1

# Install Google Chrome manually
RUN apt-get update && apt-get install -y wget gnupg --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' \
    && apt-get update && apt-get install -y google-chrome-stable --no-install-recommends \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set environment variables for Puppeteer to use the installed Chrome
ENV PUPPETEER_SKIP_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/google-chrome-stable

WORKDIR /usr/src/app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install the dependencies (this will include node-telegram-bot-api)
RUN npm install

# Copy the rest of the application files
COPY . .

# Define the command to run your bot
CMD ["node", "telegramBot.js"]
